language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - TOX_ENV=django21
  - TOX_ENV=django20
  - TOX_ENV=django111

matrix:
  exclude:
    - python: 2.7
      env: TOX_ENV=django20
    - python: 2.7
      env: TOX_ENV=django21
    - python: 3.4
      env: TOX_ENV=django21

# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
    - tox -e $TOX_ENV
